Add skeleton code as exercise example
AshciR/adapter-pattern pull request #2
Opened 2018-03-30 21:24 UTC by biddellns

- Add WeatherStation objects that report the weather for a city.

- There's a "standard" group of WeatherStations that get returned as a List.
- There's also a group of WeatherStation data provided by the NOAA. This is returned as an Array.

- The main program expects to print out a List of weather stations, so we need to convert the NOAA data structure. One (overkill) way to do this is with the adapter pattern.
--------------------------------------------------------------------------------------------------------------

I skeleton-ed this out really thoroughly I think. We might want to remove the adapter class altogether and let people create it themselves. We can discuss this more, but from this point, we can just peel back.

2018-03-30 21:26 UTC, biddellns commented
I need to refine a couple things, but this is good enough for the first PR.

2018-04-04 09:40 UTC, AshciR commented on src/com/richard/walker/weatherstation/Main.java
> +        StandardRegionalWeatherAdapter regionalWeatherAdapter = new StandardRegionalWeatherAdapter(noaaRegionalWeather);
We should return the interface, not the Adapter. It helps illustrate the conversion

2018-04-04 09:41 UTC, AshciR commented on src/com/richard/walker/weatherstation/constants/Cities.java
> +    public Cities() {
Not sure what you're trying to do here. If we want to prevent instantiation, we can privatize the constructor.

2018-04-04 09:45 UTC, AshciR commented on src/com/richard/walker/weatherstation/utilities/WeatherGenerator.java
> +        throw new UnsupportedOperationException("Constructor not implemented");
Same comment as the private constructor

2018-04-04 09:47 UTC, AshciR commented on src/com/richard/walker/weatherstation/utilities/WeatherGenerator.java
> +        ThreadLocalRandom rand = ThreadLocalRandom.current();
Your intent with this class is to generate some random data for the weather station right? Is there a particular reason why you chose to use ```ThreadLocalRandom``` class over ```java.util.Random```?

2018-04-04 09:52 UTC, AshciR commented on src/com/richard/walker/weatherstation/vendor/StandardRegionalWeatherAdapter.java
> +    public StandardRegionalWeatherAdapter(NoaaRegionalWeather noaaRegionalWeather) {
I wanna add a comment here to show that we're using dependency injection. I think it'll be beneficial to remind people that the concept isn't limited to the ```@Inject ``` annotation.

2018-04-04 09:54 UTC, AshciR requested changes
Thanks man. Looks great. There a few things I wanna discuss with you in person before I merge.

2018-04-04 14:22 UTC, merged